TN-3117 out of window proms UI changes
uwcirg/truenth-portal pull request #4170
Opened 2022-01-21 01:22 UTC by achen2401

https://jira.movember.com/browse/TN-3117

2022-01-21 01:25 UTC, achen2401 commented
@pbugni & @ivan-c Will you have a minute to try out my changes?  Let me know if you see any issue?

2022-01-21 21:44 UTC, mcjustin commented
@achen2401  I thought this was contingent on @pbugni  adding some new services?

2022-01-21 21:47 UTC, achen2401 commented
@mcjustin Yes, you are right.  This PR only addresses the frontend changes.

2022-01-21 21:51 UTC, ivan-c approved these changes
Looks good!

2022-01-21 21:51 UTC, ivan-c commented on portal/static/js/src/modules/TnthAjax.js
> +                    callback({"error": i18next.t("Error occurred retrieving assessment timeline.")});
>Error occurred retrieving assessment timeline.

If we want to translate this string, could you replace this error message with an existing (more generic) one that's already translated?

2022-01-24 20:02 UTC, pbugni commented
> @mcjustin Yes, you are right. This PR only addresses the frontend changes.

@achen2401 I was under the impression from our session on Thursday, that the existing API, namely `/api/patient/<id>/timeline` delivered all you needed for this feature.  Is there something lacking?

2022-01-24 20:09 UTC, achen2401 commented
@pbugni sorry, I am merely pointing out that there are other backend changes that still have to made based on the [specs](https://promowiki.movember.com/pages/viewpage.action?spaceKey=IR&title=Capturing+%27out+of+window%27+PROMs), i.e. **5.b.iii, 5.b.iv** This PR is purely for frontend changes.

2022-01-24 20:10 UTC, pbugni requested changes
We do NOT want to transmit "visit" information through the AE and back to the portal, but rather just dates.
- the `authored` date must be within the valid timeframe of the requested visit.  for `actual` dates outside the valid timeframe, it should be the closer fencepost (i.e. the end of the visit if it happened after, the start of the visit if it happened before).  the `authored` date will continue to be used to look up *which* visit the response belongs to.
- the `actual` date need only be included when the user selects a date outside the valid visit window.  it will just ride along, be included in the parameters passed to AE, and the AE will package w/i the QNR.

2022-02-03 21:45 UTC, pbugni approved these changes
@achen2401 looks great.  Please update the PR comment to match what is now being passed (i.e. dates and not visit info).  Thanks!

2022-02-07 22:01 UTC, merged